on: push
env:
  OLLAMA_MODEL: gemma4:e4b

jobs:
  ollama:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ollama
        uses: ai-action/setup-ollama@v2
    
      - name: Cache model
        uses: actions/cache@v5
        with:
          path: ~/.ollama
          key: ollama-action-${{ runner.os }}

      - run: ollama pull "${OLLAMA_MODEL}"
      - run: ollama run "${OLLAMA_MODEL}" "Difference between cat and dog" --think=false
      - run: ollama run "${OLLAMA_MODEL}" "Difference between cat and dog" --think=true
