on: push
jobs:
  ollama:
    runs-on: ubuntu-latest
    steps:
      - name: Run model
        uses: ai-action/ollama-action@v2
        id: model
        with:
          model: gemma4:e4b
          prompt: Can you add 2 and 2?

      - name: Print response
        run: echo "$response"
        env:
          response: ${{ steps.model.outputs.response }}
